# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # 拉取代码
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - run: /pack
    #上传Action文件
    - name: Upload Action File
      uses: actions/upload-artifact@v1.0.0
      with:
        name: MiraiMCBE
        path: tmp/MiraiMCBE.llplugin

      #发布Github Release
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: v${{env.RELEASE_TAG}}
        # body_path: ./CHANGELOG.md
        files: |
          tmp/MiraiMCBE.llplugin
      env:
          GITHUB_REPOSITORY: Nilbridge/MiraiMCBE
